[package]
name = "fast_json"
version = "0.1.0"
authors = []
build = "build.rs"

[lib]
name = "fast_json"
path = "src/lib.rs"
crate-type = ["dylib"]

[features]
default = ["with-syntex"]

with-syntex = ["rustler_codegen/with-syntex"]

[build-dependencies]
rustler_codegen = { git = "https://github.com/hansihe/Rustler" }

[dependencies]
rustler = { git = "https://github.com/hansihe/Rustler" }
rustler_codegen = { git = "https://github.com/hansihe/Rustler" }
json = "0.11.0"
